### ISSUE TITLE
multiple_slashes_are_removed fails on windows

### ISSUE THREAD

**Issue by nicolaspernoud** [casey/lexiclean#4]
Hello,

It seems multiple_slashes_are_removed test fails on windows. It is ok for the other tests...

Best regards.

**Comment by casey** [comment]
Thank you for making this issue! Very strange, I wonder if anything has changed in the way Rust handles Windows paths 🤔

I don't have a windows machine to develop on, so I'm experimenting in #5.

**Comment by casey** [comment]
Looks like a change in path parsing on Windows: https://github.com/rust-lang/rust/issues/101358

**Comment by nicolaspernoud** [comment]
Ok, thanks, just need to wait then…

**Comment by casey** [comment]
Let's keep this open until this is fixed, since otherwise users might be confused why it's failing.

**Comment by nicolaspernoud** [comment]
👍

**Comment by casey** [comment]
Fixed! See the run on this PR: https://github.com/casey/lexiclean/pull/6

Thanks for reporting this!

**Comment by nicolaspernoud** [comment]
You’re welcome. Thanks for your work !
